### ISSUE TITLE
raspir error

### ISSUE THREAD

**Issue by LisaHollstein** [MHH-RCUG/nf_wochenende#76]
Ilona and I have the same issue with raspir. It starts but creates no output files without giving any error messages or any other helpful output.

**Comment by colindaven** [comment]
Ok. 

- Which input data ? 
- Are the relevant files linked into the raspir `work` folder ?
- Does the `raspir_fileprep` complete successfully ? See `work`
- Are there enough reads in the sample for raspir ?

This is strange, because it has been working fine this side for weeks with the test fastqs from 
https://github.com/colindaven/ref_testing

**Comment by colindaven** [comment]
I just ran a lot of tests last night, and got no failures at all ... see bottom.

@LisaHollstein if you set this for` raspir and raspir_fileprep` you'll get at least the working dir to navigate to so you can check for errors. I have a feeling it might be something in the `haybaler env` used by raspir.

`	errorStrategy 'terminate'`

Please check `haybaler env`  like this
```
conda activate haybaler
conda list

--> does yours look similar ? Identical ? Please export to file, and yours too, then compare with 
vimdiff x.txt y.txt

# packages in environment at /home/hpc/davenpor/programs/miniconda3/envs/haybaler:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
biopython                 1.78                     pypi_0    pypi
black                     20.8b1                   pypi_0    pypi
blas                      1.0                         mkl
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2021.1.19            h06a4308_1
certifi                   2020.12.5        py37h89c1867_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
fastcache                 1.1.0            py37h4abf009_2    conda-forge
ffmpeg                    4.3.1                h3215721_1    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
gmp                       6.2.0                h58526e2_4    conda-forge
gmpy2                     2.1.0b1          py37hcb968a4_1    conda-forge
gnutls                    3.6.13               h79a8f9a_0    conda-forge
importlib-metadata        2.0.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        2.0.0                         1    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2022.0.1          h06a4308_3633
jack                      0.125.0           hf484d3e_1001    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_1    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0                    21_mkl    conda-forge
libcblas                  3.8.0                    21_mkl    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdb                     6.1.26                        0    bioconda
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0                    21_mkl    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_5    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h4f3a223_6    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
mad                       0.15.1b              he1b5a44_0    conda-forge
mkl                       2020.2                      256  
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
mpc                       1.1.0             h04dde30_1009    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mypy-extensions           0.4.3                    pypi_0    pypi
mysql-connector           2.2.9                    pypi_0    pypi
mysql-connector-python    8.0.21                   pypi_0    pypi
mysql-connector-python-rf 2.2.2                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
numpy                     1.19.1           py37h7ea13bd_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h8b12597_0    conda-forge
openssl                   1.1.1i               h27cfd23_0  
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.1.1            py37h3340039_0    conda-forge
pathspec                  0.8.0                    pypi_0    pypi
pillow                    7.2.0            py37h718be6c_2    conda-forge
pip                       20.2.2                     py_0    conda-forge
pluggy                    0.13.1           py37h89c1867_4    conda-forge
portaudio                 19.6.0               h1398938_3    conda-forge
protobuf                  3.13.0                   pypi_0    pypi
py                        1.10.0             pyhd3deb0d_0    conda-forge
pyaudio                   0.2.11          py37h8f50634_1002    conda-forge
pydub                     0.23.1                     py_0    conda-forge
pyparsing                 2.4.7              pyhd8ed1ab_1    conda-forge
pysam                     0.16.0.1         py37hc334e0b_1    bioconda
pytaxonkit                0.7.2                      py_0    bioconda
pytest                    6.2.2            py37h89c1867_0    conda-forge
python                    3.7.7                hcff3b4d_5  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
regex                     2020.10.15               pypi_0    pypi
scipy                     1.5.2            py37h8911b10_2    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sox                       14.4.2            h27f72bc_1013    conda-forge
sqlite                    3.32.3               h4cf870e_1    conda-forge
sympy                     1.6.2            py37h89c1867_1    conda-forge
taxonkit                  0.7.2                h9ee0642_1    bioconda
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
tornado                   6.0.4            py37h8f50634_2    conda-forge
typed-ast                 1.4.1                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

```





```

[3f/491da7] Submitted process > wochenende (ERR9809365_R1.fastq)
[da/403e8f] Submitted process > wochenende (public_mock_qsm_R1.fastq)
[38/714c47] Submitted process > wochenende (ERR9809371_R1.fastq)
[51/a45e78] Submitted process > wochenende (ERR9809360_R1.fastq)
[60/919fa6] Submitted process > wochenende (public_mock_qsm3_R1.fastq)
[35/5812de] Submitted process > wochenende (DRR_sm_R1.fastq)
[ed/c55510] Submitted process > plots (public_mock_qsm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[bd/a887bd] Submitted process > growth_rate (public_mock_qsm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[bf/94b420] Submitted process > reporting (public_mock_qsm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.txt)
[4b/e49279] Submitted process > raspir_fileprep (public_mock_qsm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[0e/d8490c] Submitted process > reporting (ERR9809371_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.txt)
[f6/b34db7] Submitted process > plots (ERR9809371_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[b1/35006c] Submitted process > raspir_fileprep (ERR9809371_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[fb/354d96] Submitted process > growth_rate (ERR9809371_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[db/b4d3e8] Submitted process > raspir (public_mock_qsm_R1.ndp.trm.s.mm.dup.mq30.calmd.raspir.csv)
[d9/9e91c2] Submitted process > raspir (ERR9809371_R1.ndp.trm.s.mm.dup.mq30.calmd.raspir.csv)
[2f/eb0a2a] Submitted process > reporting (public_mock_qsm3_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.txt)
[19/4b6524] Submitted process > raspir_fileprep (public_mock_qsm3_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[cf/ec2858] Submitted process > plots (public_mock_qsm3_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[03/0d42ea] Submitted process > growth_rate (public_mock_qsm3_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[e4/4345a6] Submitted process > reporting (ERR9809360_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.txt)
[cb/de617f] Submitted process > plots (ERR9809360_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[98/5ab41d] Submitted process > raspir_fileprep (ERR9809360_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[4a/5d2801] Submitted process > growth_rate (ERR9809360_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[8a/29fde7] Submitted process > raspir (public_mock_qsm3_R1.ndp.trm.s.mm.dup.mq30.calmd.raspir.csv)
[9a/c54078] Submitted process > reporting (DRR_sm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.txt)
[34/95c8bd] Submitted process > plots (DRR_sm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[57/eaaaa9] Submitted process > raspir_fileprep (DRR_sm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[73/80afcc] Submitted process > growth_rate (DRR_sm_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[54/8c2b65] Submitted process > raspir (DRR_sm_R1.ndp.trm.s.mm.dup.mq30.calmd.raspir.csv)
[61/d0aadf] Submitted process > raspir (ERR9809360_R1.ndp.trm.s.mm.dup.mq30.calmd.raspir.csv)
[63/c993a7] Submitted process > plots (ERR9809365_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[c5/defbb1] Submitted process > growth_rate (ERR9809365_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[2b/8ad925] Submitted process > raspir_fileprep (ERR9809365_R1.ndp.trm.s.mm.dup.mq30.calmd.bam)
[26/51b4e7] Submitted process > reporting (ERR9809365_R1.ndp.trm.s.mm.dup.mq30.calmd.bam.txt)
[24/f82deb] Submitted process > raspir (ERR9809365_R1.ndp.trm.s.mm.dup.mq30.calmd.raspir.csv)
[c9/1bf926] Submitted process > haybaler (haybaler_input)
```

**Comment by LisaHollstein** [comment]
> 
>     * Which input data ? 
Jufo and also some data from Ilona (growth rate worked with that data)
> 
>     * Are the relevant files linked into the raspir `work` folder ? 
yes
> 
>     * Does the `raspir_fileprep` complete successfully ? See `work`
yes
> 
>     * Are there enough reads in the sample for raspir ?
I think so
> 
> 
> This is strange, because it has been working fine this side for weeks with the test fastqs from https://github.com/colindaven/ref_testing
I do not think that the data is the problem. `raspir.py` does not run for whatever reason (it is in the right work directory). in the .command.out there is nothing, even though I modified `raspir.py` to print something as soos as it is started

**Comment by LisaHollstein** [comment]
> --> does yours look similar ? Identical ? Please export to file, and yours too, then compare with
It's similar, but not identical

**Comment by LisaHollstein** [comment]
I created a new haybaler conda env with the current version of  `env.haybaler.yml` and now I get : `ModuleNotFoundError: No module named 'matplotlib'`

I only wonder why this isn't an issue for you, since your conda environment doesn't seem to include matplotlib as well (and also I have the newest version of the haybaler conda env)

**Comment by colindaven** [comment]
Ah, that could be it. It should throw an error though when you do 
bash runbatch_raspir.sh or python3 raspir.py in the work directory (you can get the exact command from `.command.sh `I think.

Can you  add these two to your haybaler env locally and reinstall the env ?

```
when in haybaler_env
mamba install matplotlib
```

```

  - matplotlib=3.3.4=py37h06a4308_0
  - matplotlib-base=3.3.4=py37h62a2d02_0
```

**Comment by colindaven** [comment]
Just checked, scipy should be ok, but please add the matplotlib version you get installed to

https://github.com/MHH-RCUG/haybaler/blob/dev/env.haybaler.yml

Thanks and sorry about this one ...

**Comment by LisaHollstein** [comment]
I have some problems with adding matplotlib to the env:
```
Encountered problems while solving:
  - package matplotlib-base-3.3.4-py37h62a2d02_0 requires freetype >=2.10.4,<3.0a0, but none of the providers can be installed
```

**Comment by LisaHollstein** [comment]
But running the raspir stage with the raspir conda env works, so the problem is definetly just the conda env!

**Comment by colindaven** [comment]
`mamba install -c conda-forge matplotlib`

does that pull in the freetype ?

Ok great, good to know what the problem is

**Comment by LisaHollstein** [comment]
`mamba install -c conda-forge matplotlib` does not work either

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/ngsnfs/gen/rcug_lw/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/mnt/ngsnfs/gen/rcug_lw/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 898, in exception_converter
        raise e
      File "/mnt/ngsnfs/gen/rcug_lw/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 892, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/mnt/ngsnfs/gen/rcug_lw/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 851, in _wrapped_main
        result = do_call(args, p)
      File "/mnt/ngsnfs/gen/rcug_lw/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 732, in do_call
        exit_code = install(args, parser, "install")
      File "/mnt/ngsnfs/gen/rcug_lw/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 590, in install
        downloaded = transaction.prompt(repos)
    RuntimeError: Found incorrect download. Aborting

`$ /mnt/ngsnfs/gen/rcug_lw/miniconda3/condabin/mamba install -c conda-forge matplotlib`

  environment variables:
     AUGUSTUS_CONFIG_PATH=/mnt/ngsnfs/tools/augustus-3.2.1/config/
      AUTOJUMP_ERROR_PATH=/home/rcug_lw/.local/share/autojump/errors.log
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=haybaler_new
                CONDA_EXE=/mnt/ngsnfs/gen/rcug_lw/miniconda3/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/mnt/ngsnfs/gen/rcug_lw/miniconda3/envs/haybaler_new
    CONDA_PROMPT_MODIFIER=(haybaler_new)
         CONDA_PYTHON_EXE=/mnt/ngsnfs/gen/rcug_lw/miniconda3/bin/python
               CONDA_ROOT=/mnt/ngsnfs/gen/rcug_lw/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=/mnt/ngsnfs/tools/miniconda3/etc/pki/tls/certs/
       DRMAA_LIBRARY_PATH=/usr/lib/slurm-drmaa/lib/libdrmaa.so
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
          LD_LIBRARY_PATH=/mnt/ngsnfs/tools/mpich-3.1.4/mpich-3.1.4/lib:/mnt/ngsnfs/tools/jemall
                          oc/lib:/mnt/ngsnfs/tools/jellyfish/lib:/mnt/ngsnfs/tools/root/root/lib
                          :/mnt/ngsnfs/tools/openmpi/openmpi-1.8.1/lib:/mnt/ngsnfs/tools/bambamc
                          /lib:/usr/lib:/mnt/ngsnfs/tools/salmon/build/lib:/usr/lib/x86_64-linux
                          -gnu/:
                     PATH=/mnt/ngsnfs/gen/rcug_lw/miniconda3/envs/haybaler_new/bin:/home/rcug_lw
                          /bin:/home/rcug_lw/.local/bin:/mnt/ngsnfs/gen/rcug_lw/miniconda3/conda
                          bin:/mnt/ngsnfs/tools/gmap/gmap-2016-09-23/bin:JRE_HOME/bin:/mnt/ngsnf
                          s/tools/nextflow:/mnt/ngsnfs/tools/drop-seq-tools/Drop-seq_tools-1.13:
                          /mnt/ngsnfs/tools/vg/vg/bin:/mnt/ngsnfs/tools/bbmap38.75:/mnt/ngsnfs/t
                          ools/SPRING/build:/mnt/ngsnfs/tools/deSALT/src:/mnt/ngsnfs/tools/bwa-
                          mem2/bwa-mem2-2.0pre1_x64-linux:/mnt/ngsnfs/tools/cellranger/cellrange
                          r-3.0.2:/mnt/ngsnfs/tools/gencore:/mnt/ngsnfs/tools/tardis/tardis:/mnt
                          /ngsnfs/tools/bamscale:/mnt/ngsnfs/tools/bigwig:/mnt/ngsnfs/tools/samt
                          ools-1.8:/mnt/ngsnfs/tools/bowtie2/bowtie2-2.4.4-linux-x86_64:/mnt/ngs
                          nfs/tools/genmap:/mnt/ngsnfs/tools/shasta:/mnt/ngsnfs/tools/slivar:#/m
                          nt/ngsnfs/tools/bcl2fastq:/mnt/ngsnfs/tools/bcl2fastq2-v2.20.0.422/bin
                          :/mnt/ngsnfs/tools/FastQC_v0.11.9:/mnt/ngsnfs/tools/tardis/mrfast:/mnt
                          /ngsnfs/tools/uxy/uxy:/mnt/ngsnfs/tools/git-lfs:/mnt/ngsnfs/tools/flap
                          pie:/mnt/ngsnfs/tools/bless/v1p02:/mnt/ngsnfs/tools/ntedit/nthits:/mnt
                          /ngsnfs/tools/ntedit/ntedit:/mnt/ngsnfs/tools/whisper:/mnt/ngsnfs/tool
                          s/duphold:/mnt/ngsnfs/tools/ra/ra/build/bin:/mnt/ngsnfs/tools/NanoVar/
                          scripts:/mnt/ngsnfs/tools/cobalt/bin:/mnt/ngsnfs/tools/biscuit:/mnt/ng
                          snfs/tools/seqkit:/mnt/ngsnfs/tools/proovread/bin:/mnt/ngsnfs/tools/ne
                          ofetch/neofetch-3.3.0:/mnt/ngsnfs/tools/flye/Flye-2.3/bin:/mnt/ngsnfs/
                          tools/spades/SPAdes-3.11.0-Linux/bin:/mnt/ngsnfs/tools/mummer4/mummer-
                          4.0.0beta2/bin/bin:/mnt/ngsnfs/tools/julia/julia-1.1.0/bin:/mnt/ngsnfs
                          /tools/fastp/fastp:/mnt/ngsnfs/tools/elPrep/elprep4:/mnt/ngsnfs/tools/
                          icgc:/mnt/ngsnfs/tools/gotop:/mnt/ngsnfs/tools/defiant/defiant:/mnt/ng
                          snfs/tools/TRF:/mnt/ngsnfs/tools/REPET/REPET_linux-x64-2.2:/mnt/ngsnfs
                          /tools/lumpy-sv/bin:/mnt/ngsnfs/tools/bayestyper/bayesTyper_v1.3.1_lin
                          ux_x86_64/bin:/mnt/ngsnfs/tools/RepeatMasker/RepeatMasker:/mnt/ngsnfs/
                          tools/RepeatModeler/RepeatScout/RepeatScout-1:/mnt/ngsnfs/tools/genome
                          tools/bin:/mnt/ngsnfs/tools/smoove:/mnt/ngsnfs/tools/RECON/RECON-1.08:
                          /mnt/ngsnfs/tools/RECON/RECON-1.08/scripts:/mnt/ngsnfs/tools/PILER:/mn
                          t/ngsnfs/tools/hercules/bin:/mnt/ngsnfs/tools/indexcov:/mnt/ngsnfs/too
                          ls/mpich-3.1.4/mpich-3.1.4/bin:/mnt/ngsnfs/tools/openmpi-1.8.1/bin:/mn
                          t/ngsnfs/tools/parallel/parallel-20141122/bin:/mnt/ngsnfs/tools/STAR/S
                          TAR_2_5_1/STAR/bin/Linux_x86_64_static:/mnt/ngsnfs/tools/cufflinks-2.2
                          .1.Linux_x86_64:/mnt/ngsnfs/tools/fastx/bin:/mnt/ngsnfs/tools/trinity/
                          trinityrnaseq-2.0.6:/mnt/ngsnfs/tools/diamond_7.9:/mnt/ngsnfs/tools/me
                          raculous/bin:/mnt/ngsnfs/tools/aragorn1.2.36:/mnt/ngsnfs/tools/tbl2asn
                          :/mnt/ngsnfs/tools/mauve_snapshot_2015-02-13/linux-x64:/mnt/ngsnfs/too
                          ls/ngsutils/ngsutils-ngsutils-0.5.7/bin:/mnt/ngsnfs/tools/malt:/mnt/ng
                          snfs/tools/mugsy_latest:/mnt/ngsnfs/tools/last/last/bin:/mnt/ngsnfs/to
                          ols/Lighter:/mnt/ngsnfs/tools/micro:#/mnt/ngsnfs/tools/blast-2.2.26/bi
                          n:/mnt/ngsnfs/tools/blast/ncbi-
                          blast-2.4.0+/bin:/mnt/ngsnfs/tools/ncbi_blast_plus/ncbi-
                          blast-2.7.1_plus/bin:/mnt/ngsnfs/tools/lastz-distrib-1.02.00/bin:/mnt/
                          ngsnfs/tools/MUMmer3.23:/mnt/ngsnfs/tools/trig/trig-1.0/bin:/mnt/ngsnf
                          s/tools/Metassembler_1.5/bin:/mnt/ngsnfs/tools/allmaps:/mnt/ngsnfs/too
                          ls/pindel:/mnt/ngsnfs/tools/trim_galore/TrimGalore:/mnt/ngsnfs/tools/R
                          /R-3.2.2/bin:/mnt/ngsnfs/tools/bcftools-1.2:/mnt/ngsnfs/tools/vcftools
                          /bin:/mnt/ngsnfs/tools/dos2unix-7.3.2:/mnt/ngsnfs/tools/cdhit:/mnt/ngs
                          nfs/tools/clustal_omega:/mnt/ngsnfs/tools/FastUniq/source:/mnt/ngsnfs/
                          tools/bamtools/bin:/mnt/ngsnfs/tools/augustus-3.2.1/bin:/mnt/ngsnfs/to
                          ols/BISMARK/Bismark:/mnt/ngsnfs/tools/cutadapt/cutadapt-1.9.1/bin:/mnt
                          /ngsnfs/tools/root/root/bin:/mnt/ngsnfs/tools/aseq/binaries/linux64:/m
                          nt/ngsnfs/tools/vt/vt:/mnt/ngsnfs/tools/snap:/mnt/ngsnfs/tools/bedtool
                          s/bedtools-2.30.0:/mnt/ngsnfs/tools/quickmerge/quickmerge/merger:/mnt/
                          ngsnfs/tools/ucsc:/mnt/ngsnfs/tools/sra-tools/sratoolkit.2.6.3-ubuntu6
                          4/bin:/mnt/ngsnfs/tools/bedops/bin:/mnt/ngsnfs/tools/smalt-0.7.6/bin:/
                          mnt/scratch/ensembl-vep/htslib:/mnt/ngsnfs/tools/fasta-36.3.8e/bin:/mn
                          t/ngsnfs/tools/fastme-2.1.5/binaries:/mnt/ngsnfs/tools/PASApipeline/bi
                          n:/mnt/ngsnfs/tools/cmake-3.7.0-rc1/bin:/mnt/ngsnfs/tools/jdk-10.0.1/b
                          in:/mnt/ngsnfs/tools/subread/subread-1.5.1-Linux-x86_64/bin:/mnt/ngsnf
                          s/tools/salmon/build/bin:/mnt/ngsnfs/tools/Slurm_tools/partitions:/mnt
                          /ngsnfs/tools/Slurm_tools/slurmreportmonth:/mnt/ngsnfs/tools/Slurm_too
                          ls/pestat:/mnt/ngsnfs/tools/Slurm_tools/showuserjobs:/home/rcug_lw/bin
                          :/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/gam
                          es:/usr/local/games:/snap/bin
               REPET_PATH=/mnt/ngsnfs/tools/REPET_linux-x64-2.2/
       REQUESTS_CA_BUNDLE=<not set>
     SINGULARITY_BINDPATH=/ngsssd1/rcug_lw,/working2/rcug_lw
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : haybaler_new
    active env location : /mnt/ngsnfs/gen/rcug_lw/miniconda3/envs/haybaler_new
            shell level : 1
       user config file : /home/rcug_lw/.condarc
 populated config files : /home/rcug_lw/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/ngsnfs/gen/rcug_lw/miniconda3  (writable)
      conda av data dir : /mnt/ngsnfs/gen/rcug_lw/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/ngsnfs/gen/rcug_lw/miniconda3/pkgs
                          /home/rcug_lw/.conda/pkgs
       envs directories : /mnt/ngsnfs/gen/rcug_lw/miniconda3/envs
                          /home/rcug_lw/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.25.1 CPython/3.9.1 Linux/5.4.0-107-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 9419:9419
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by colindaven** [comment]
retry, proxy server error ?

And or 

`mamba clean `

then retry

**Comment by LisaHollstein** [comment]
Got the same error

**Comment by colindaven** [comment]
just installed successfully with a different conda channel (not conda-forge, bioconda)

`mamba install -c bioconda matplotlib`

**Comment by colindaven** [comment]
or just add
`  - matplotlib=3.5.3`
to your haybaler env and reinstall, hope one option works on your system.
